### ISSUE TITLE
Dependency Communication-Calling 1.0.0-beta.7 not available

### ISSUE THREAD

**Issue by qzzf1w** [Azure-Samples/communication-services-web-calling-tutorial#20]
@azure/communication-calling": "1.0.0-beta.7",

Dependencies fail to install dependencies - package not available 

@chriswhilar    I believe you just checked this in #19

**Comment by akania** [comment]
Hi @qzzf1w 1.0.0-beta.7 was deprecated due to an issue, please downgrade to 1.0.0-beta.6
we'll fix sample code soon
