### ISSUE TITLE
Join Teems Meeting Fails

### ISSUE THREAD

**Issue by qzzf1w** [Azure-Samples/communication-services-web-calling-tutorial#21]
Built and Running the App.

Using communication-calling": "1.0.0-beta.6"

Have created a Teams meeting.
Am in it.

Try joining via meeting link.

If no one is in the meeting, I will be put in lobby,
When I am let in things work well.
Great!

If someone is already in the meeting 
When I try to join via ACS I get

Call end reason: code: 403, subcode: 5221

How can I avoid this?

Thanks

**Comment by akania** [comment]
Hi @qzzf1w , did you enable your Teams tenant for ACS interop ? 
Public documentation has a link to a Form that you have to submit in order to do that - https://docs.microsoft.com/en-us/azure/communication-services/concepts/teams-interop

**Comment by shehaniperera** [comment]
Initially was able to connect to a teams meeting using the sample. However, after trying continuously , unable to connect with teams meeting call. Tried regenerating the keys however call ends.  Call end reason: code: 403, subcode: 5222

**Comment by ddematheu2** [comment]
Closing due to no additional activity.
