### ISSUE TITLE
Joining Teams Meeting with Azure Communication service fails

### ISSUE THREAD

**Issue by shehaniperera** [Azure-Samples/communication-services-web-calling-tutorial#27]
Initially was able to connect to a teams meeting using the sample and it worked fine. However, after trying continuously , unable to connect with teams meeting call. Tried regenerating the keys however call ends. Call end reason: code: 403, subcode: 5222

**Comment by ddematheu2** [comment]
Please make sure that you have enabled your ACS resource to use Teams interoperability. https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR21ouQM6BHtHiripswZoZsdURDQ5SUNQTElKR0VZU0VUU1hMOTBBMVhESS4u
