### ISSUE TITLE
Calling phone number fails with " Call end reason: code: 500, subcode: 511404"

### ISSUE THREAD

**Issue by dochoss** [Azure-Samples/communication-services-web-calling-tutorial#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> cloned repo 
> cd communication-services-web-calling-tutorial/Project
> npm install
> npm run build
> npm run start
> entered my personal cell phone number into "Destination Phone Identity or Phone Identities" input field
> entered another personal cell phone (my wife's number) into "Alternate Caller Id (For calling phone numbers only)" input field
> clicked Place Call
I can't find any guidance on how to enter phone numbers.  Should I include region code like +1 for US or not?  Neither seems to work, and including `+1` vs `1` doesn't seem to help.

### Any log messages given by the failure
> Red error alert box appears with text: "Call end reason: code: 500, subcode: 511404"

### Expected/desired behavior
> Phone call completes

### OS and Version?
> Windows 10. 

### Versions
> Node version 12.13.1.  npm version 6.12.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aaronse** [comment]
+1

**Comment by chriswhilar** [comment]
"Alternate Caller Id (For calling phone numbers only)" is the phone number associated with your azure resource connection string.

"Destination Phone Identity or Phone Identities" is the phone number you are calling to
