### ISSUE TITLE
Quickstart fails at npm install step

### ISSUE THREAD

**Issue by JuiceyDuecy** [Azure-Samples/communication-services-web-calling-tutorial#42]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> git clone "repo"
> npm install 

### Any log messages given by the failure
>
 npm install

> contextify@0.1.15 install C:\Users\copennin\node_modules\contextify
> node-gyp rebuild

C:\Users\copennin\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.cc
c:\users\copennin\node_modules\contextify\src\contextify.cc(52): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\context
ify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(6482): note: see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(52): error C2661: 'v8::Object::Set': no overloaded function takes 1 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj] 
c:\users\copennin\node_modules\contextify\src\contextify.cc(62): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]   
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(62): error C2512: 'ContextifyContext::ContextifyContext': no appropriate default constructor available [C:\Users\copennin\node_modules\contextify\ 
build\contextify.vcxproj]
c:\users\copennin\node_modules\contextify\src\contextify.cc(77): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]   
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2810): note: see declaration of 'v8::Value::ToString' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(83): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]   
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2810): note: see declaration of 'v8::Value::ToString' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(83): error C2512: 'v8::ScriptOrigin::ScriptOrigin': no appropriate default constructor available [C:\Users\copennin\node_modules\contextify\build\ 
contextify.vcxproj]
c:\users\copennin\node_modules\contextify\src\contextify.cc(126): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contex 
tify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(6482): note: see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(126): error C2660: 'Nan::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>::Reset': function does not take 1 arguments [C:\Users\copenni 
n\node_modules\contextify\build\contextify.vcxproj]
          with
          [
              T=v8::Function
          ]
  c:\users\copennin\node_modules\nan\nan_persistent_12_inl.h(25): note: see declaration of 'Nan::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>::Reset'
          with
          [
              T=v8::Function
          ] (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(131): error C2661: 'v8::Function::NewInstance': no overloaded function takes 0 arguments [C:\Users\copennin\node_modules\contextify\build\contexti 
fy.vcxproj]
c:\users\copennin\node_modules\contextify\src\contextify.cc(140): error C2039: 'SetHiddenPrototype': is not a member of 'v8::FunctionTemplate' [C:\Users\copennin\node_modules\contextify\build\contextify.vcx 
proj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(6461): note: see declaration of 'v8::FunctionTemplate'
c:\users\copennin\node_modules\contextify\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate' [C:\Users\copennin\node_modules\contextify\build\contextify. 
vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(6754): note: see declaration of 'v8::ObjectTemplate'
c:\users\copennin\node_modules\contextify\src\contextify.cc(176): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(182): error C2660: 'v8::Object::GetRealNamedProperty': function does not take 1 arguments [C:\Users\copennin\node_modules\contextify\build\context 
ify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(3988): note: see declaration of 'v8::Object::GetRealNamedProperty' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(192): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(198): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj 
]
c:\users\copennin\node_modules\contextify\src\contextify.cc(203): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(209): error C2660: 'v8::Object::GetRealNamedProperty': function does not take 1 arguments [C:\Users\copennin\node_modules\contextify\build\context 
ify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(3988): note: see declaration of 'v8::Object::GetRealNamedProperty' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(210): error C2660: 'v8::Object::GetRealNamedProperty': function does not take 1 arguments [C:\Users\copennin\node_modules\contextify\build\context 
ify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(3988): note: see declaration of 'v8::Object::GetRealNamedProperty' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(218): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(224): error C2661: 'v8::Object::Delete': no overloaded function takes 1 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxp 
roj]
c:\users\copennin\node_modules\contextify\src\contextify.cc(229): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(237): error C2661: 'v8::Object::GetPropertyNames': no overloaded function takes 0 arguments [C:\Users\copennin\node_modules\contextify\build\conte 
xtify.vcxproj]
c:\users\copennin\node_modules\contextify\src\contextify.cc(277): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contex 
tify.vcxproj]
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(6482): note: see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(277): error C2661: 'v8::Object::Set': no overloaded function takes 1 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj 
]
c:\users\copennin\node_modules\contextify\src\contextify.cc(286): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2810): note: see declaration of 'v8::Value::ToString' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(291): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2810): note: see declaration of 'v8::Value::ToString' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(319): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
c:\users\copennin\node_modules\contextify\src\contextify.cc(322): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Users\copennin\node_modules\contextify\build\contextify.vcxproj]  
  c:\users\copennin\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2822): note: see declaration of 'v8::Value::ToObject' (compiling source file ..\src\contextify.cc)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\copennin\node_modules\contextify
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN copennin@1.0.0 No description
npm WARN copennin@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.15 (node_modules\contextify):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.15 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 58 packages in 4.734s

2 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\copennin\communication-services-web-calling-tutorial> 

### Expected/desired behavior
> A clean installation

### OS and Version?
>Windows 11 21H2

### Versions
> 
 npm 6.14.15
 node v14.17.6
 
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fizampou** [comment]
Can you try to pull once more latest and run 

`npm install`

again
