### ISSUE TITLE
https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'

### ISSUE THREAD

**Issue by pellesantiago** [Azure-Samples/communication-services-web-calling-tutorial#8]
### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Start the web example and then press "Provision user and initialize SDK"

### Any log messages given by the failure
> RestError: The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'.
 {
  "name": "RestError",
  "code": "UnsupportedApiVersion",
  "statusCode": 400,
  "request": {
    "streamResponseBody": false,
    "url": "https://contactfinder-communicationservice.communication.azure.com/identities?api-version=2020-07-20-preview2",
    "method": "POST",
    "headers": {
      "_headersMap": {
        "content-type": "application/json; charset=utf-8",
        "user-agent": "azsdk-js-communication-administration/2020-07-20-preview2 core-http/1.1.8 Node/v10.15.3 OS/(x64-Windows_NT-10.0.19041)",   
        "x-ms-client-request-id": "08137f78-92a3-404e-9a56-6cd43c550143",
        "host": "REDACTED",
        "date": "Thu, 14 Jan 2021 22:01:20 GMT",
        "x-ms-content-sha256": "REDACTED",
        "authorization": "REDACTED",
        "cookie": "REDACTED"
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "requestId": "08137f78-92a3-404e-9a56-6cd43c550143"
  },
  "details": {
    "error": {
      "code": "UnsupportedApiVersion",
      "message": "The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'.",
      "innerError": null
    }
  },
  "message": "The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'."
}

### Expected/desired behavior
> Get identity and connect correctly to ACS

### OS and Version?
> Windows 10 and Chrome Versión 87.0.4280.88 (Build oficial) (64 bits)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ddematheu2** [comment]
Thanks for reporting the issue. We are currently investigating. This is an issue with the underlying SDKs being tracked here: https://github.com/Azure/Communication/issues/160

**Comment by ytyeason** [comment]
This issue should now be resolved. Please verify if possible. We'll revisit tomorrow and if everything is okay, we'll close this one out tomorrow. Thanks.

**Comment by pellesantiago** [comment]
Yes, is working! Thanks! have a nice day!
